[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H723VG"
rustflags = [
  "-C", "link-arg=-Tlink.x", # linker file
  "-C", "link-arg=--nmagic", # no std memory layout
  "-C", "link-arg=-Tdefmt.x", # add defmt
]

[build]
target = "thumbv7em-none-eabihf"


