[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32G0B1KE --host ws://open-lst-1.flatsat.space --token CHANGE_ME"
rustflags = [
  "-C", "link-arg=-Tlink.x", # linker file
  "-C", "link-arg=--nmagic", # no std memory layout
  "-C", "link-arg=-Tdefmt.x", # add defmt
]

[build]
target = "thumbv6m-none-eabi"

[net]
git-fetch-with-cli = true
